### ISSUE TITLE
Does it have an ObsoleteAnalyzer?

### ISSUE THREAD

**Issue by jzabroski** [304NotModified/ObsoleteFixer#4]
Hi Julian (@304NotModified ),

If you allow us to ship an ObsoleteAnalyzer extension with our open source projects, this could be very useful.

What I'm thinking is something like open source projects creating a package called YourProject.ObsoleteAnalyzer

```c#
public class FluentMigratorObsoleteAnalyzer : ObsoleteAnalyzer { }
```

Then, similar to how other projects like xunit ship analyzers, FluentMigrator package can ship a private asset for FluentMigrator.ObsoleteAnalyzer.

The idea is to allow projects to easily scope these obsolescence warnings to just code in their namespaces.

Maybe there is a better way , but let's brainstorm ([300MultipleChoices](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/300)).

**Comment by 304NotModified** [comment]
Sounds good!

> If you allow us to ship an ObsoleteAnalyzer extension with our open source projects, this could be very useful

Of course this is allowed, it's licensed under MIT :) (OSS FTW)

I not sure if this is fixer mature enough but I really like to have some real life feedback so we make it mature. 

Also the idea was to ship this with NLog (or make it at least compatible with). There are many obsolete methods and classes there.

**Comment by 304NotModified** [comment]
> The idea is to allow projects to easily scope these obsolescence warnings to just code in their namespaces.

If we scope this only to one project, we could also add another attribute (next to obsolete attribute) to the code. Or is that making the dependency to direct?

**Comment by jzabroski** [comment]
Yeah, you can see some of my use cases are actually more complicated than what you demonstrate here - but I LOVE your idea.

As an example, older versions of FluentMigrator supported a ApplicationContext parameter, which really isn't needed now that DependencyInjection is supported (just inject whatever unlimited contexts you want).

You can see my GitHub issue here: https://github.com/fluentmigrator/fluentmigrator/issues/1037

In the DI use case, I might want some way to generate a whole scaffolding for the user. -- Not sure if that's too opinionated.  If this were legacy .NET Framework days without any good practices around DI, I'd definitely say it's too opinionated.  But we've grown up as a community and are on par with Java Runtime as far as standards go.

**Comment by jzabroski** [comment]
Just thinking:

Right now your analyzer hard-codes a single kind of transformation option, using a single transformation context (as far as I can tell, it only allows moving from one method overload to another?).

I think ObsoleteAnalyzer v2 should support:
* Multiple transformation contexts (look at whether project as a whole is using dependency injection, if it is, use that)
* Multiple transformation options - using a different overload is great and very helpful, but if we could plug in our own code transformers, that'd be great, too.

If we make this more flexible, it probably DOES make sense to allow us to just include as a private asset a generic ObsoleteAnalyzer package.  There would be some default analyzers that don't require special logic.  Then, if you have sophisticated Transformers you'd have ObsoleteAnalyzer as a private dependency to say FluentMigrator.ObsoleteAnalyzer.

**Comment by jzabroski** [comment]
> > The idea is to allow projects to easily scope these obsolescence warnings to just code in their namespaces.
> 
> If we scope this only to one project, we could also add another attribute (next to obsolete attribute) to the code. Or is that making the dependency to direct?

I don't have the precise answer, but how does `JetBrains.Annotations` wipe away references at deploy time?  See here: https://www.nuget.org/packages/Jetbrains.Annotations/

> All usages of ReSharper Annotations attributes are erased from metadata by default, which means no actual binary reference to 'JetBrains.Annotations.dll' assembly is produced. If you need to preserve these attributes in metadata, just define 'JETBRAINS_ANNOTATIONS' conditional compilation symbol in your projects.

I'm not sure how they do this, to be honest - this is some pretty magical stuff that is just on the boundary of my knowledge of C#.

**Comment by 304NotModified** [comment]
> As an example, older versions of FluentMigrator supported a ApplicationContext parameter, which really isn't needed now that DependencyInjection is supported (just inject whatever unlimited contexts you want).

So the ApplicationContext  needs to be replaced with (multiple) constructor arguments? Or do you injection ApplicationContext  itself? (guess not)



> Right now your analyzer hard-codes a single kind of transformation option, using a single transformation context (as far as I can tell, it only allows moving from one method overload to another?).

I could change a method invocation to another method invocation with parameter transformations, so not only overloads. But it's built now that the obsolete attribute is context independent 

> * Multiple transformation contexts (look at whether project as a whole is using dependency injection, if it is, use that)
> * Multiple transformation options - using a different overload is great and very helpful, but if we could plug in our own code transformers, that'd be great, too.

Those sounds great, I think it would be easier to discuss if we have some examples :)

> I don't have the precise answer, but can we solve the problem by avoiding it: How does `JetBrains.Annotations` wipe away references at deploy time? See here: https://www.nuget.org/packages/Jetbrains.Annotations/

I think this just PrivateAssets and also the [ConditionalAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute?view=netframework-4.8). I see `[Conditional("JETBRAINS_ANNOTATIONS")]` in the decompiled source

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

**Comment by jzabroski** [comment]
> I could change a method invocation to another method invocation with parameter transformations, so not only overloads. But it's built now that the obsolete attribute is context independent

I understand - `ObsoleteAttribute` is a sealed class and we cannot extend it, so you chose to parse the Reason field. I also understand that as the refactoring suggestion gets more sophisticated, it's a bit much to stuff all the hints required to perform a multi-stage micro-refactoring in the Reason field.  Perhaps the ObsoleteAnalyzer could stuff a GistReference that's basically a gist which is a snippet to fix the code.  GistReference would be like PackageReference but for gists.  Paket does this, but Nuget does not, because Nuget is a bit stuck up about sharing snippets vs. dlls.

I'm just brainstorming ideas.

As a brief illustration of how I think: Years ago, Calgary, Alberta was facing a serious problem where the telephone wires above ground would fall due to heavy freezing rain weighing down the wires.  Nobody could figure out an economical solution to the problem. That's when they hired a consultant who brought the entire company in the room and instituted a [few basic improv rules](https://pantheater.com/rules-of-improv.html):

1. Say “Yes’and!”
2. After the “‘and,” add new information.
3. Don’t Block.
4. Avoid Questions.
5. Focus on the Here and Now.
6. Establish the Location!
7. Be Specific- Provide Details!

With this framework, a suggestion that was started by a janitor evolved into a solution that solved the problem.

**Comment by jzabroski** [comment]
@304NotModified 300MultipleChoices just got a 301PermanentRedirect!

There is a new Roslyn feature for first-class C# Source Code Generators, with full access to the C# symbol tree: https://github.com/dotnet/roslyn/blob/features/source-generators/docs/features/source-generators.md

One idea is to borrow from Paul Louth's [language-ext](https://github.com/louthy/language-ext/wiki/Code-generation) project.  Here, he uses partial classes.  I wonder if we could decorate a partial class with a Delegate signature to describe refactoring rules.

Here is some similar code from FluentMigrator to help inspire us:

#### Definition
```c#
    public class MigrationConstraintAttribute : Attribute
    {
        private readonly Func<MigrationConstraintContext, bool> _predicate;

        /// <summary>
        /// Initializes a new instance of the <see cref="MigrationConstraintAttribute"/> class.
        /// </summary>
        /// <param name="predicate">Predicate that determines whether this migration should be run in given context <see cref="MigrationConstraintAttribute"/>.</param>
        public MigrationConstraintAttribute(Func<MigrationConstraintContext, bool> predicate)
        {
            _predicate = predicate ?? throw new ArgumentNullException("predicate", "Predicate must not be null");
        }
        /// <summary>
        /// Determines whether the migration having this attribute should be run under given <paramref name="context">migration context</paramref>.
        /// </summary>
        /// <param name="context">Contextual information that can be used to determine whether this migration should be run.</param>
        /// <returns>True if migration should be run under given <paramref name="context">migration context</paramref>.</returns>
        public bool ShouldRun(MigrationConstraintContext context)
        {
            return _predicate(context);
        }
    }
```

#### Usage:

```c#
    /// <summary>
    /// Specifies minimum schema version against which this migration will be run.
    /// </summary>
    public class CurrentVersionMigrationConstraintAttribute : MigrationConstraintAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentVersionMigrationConstraintAttribute"/> class.
        /// </summary>
        /// <param name="minimumVersionToRunAgainst">The schema must equal or greater to this value for this migration to be run.</param>
        public CurrentVersionMigrationConstraintAttribute(long minimumVersionToRunAgainst)
            : base(ctx => ctx.VersionInfo.Latest() >= minimumVersionToRunAgainst) {
        }

    }
```

The idea being that similar to how you can set-up a Moq insance to return an arbitrary value, we could have an API to forward a type call to an arbitrary expression.

For some inspiration on that, look at: [erecruit.Expr](https://github.com/fsoikin/erecruit.Expr).  This library contains a way to easily quote C# code inline, without all the noise of RoslynQuoter.  It also provides a `Expr.Subst` method for doing expression tree transformations.

**Comment by 304NotModified** [comment]
> @304NotModified 300MultipleChoices just got a 301PermanentRedirect!

😆 



> There is a new Roslyn feature for first-class C# Source Code Generators, with full access to the C# symbol tree: https://github.com/dotnet/roslyn/blob/features/source-generators/docs/features/source-generators.md
> 
> One idea is to borrow from Paul Louth's [language-ext](https://github.com/louthy/language-ext/wiki/Code-generation) project. Here, he uses partial classes. I wonder if we could decorate a partial class with a Delegate signature to describe refactoring rules.
> 
> Here is some similar code from FluentMigrator to help inspire us:

Thanks, I will read them soon :)

**Comment by 304NotModified** [comment]
I'm sorry but I forgot a bit about this one. I don't have any plans for investing this for this unfortunately
